version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-southeast-1:394576591249:task-definition/ReadTaskDefinition:40"
        LoadBalancerInfo:
          ContainerName: "Fargate-Sec"
          ContainerPort: 80
        PlatformVersion: "LATEST"