version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-southeast-1:<<your account ID>>:task-definition/ReadTaskDefinition:<<Latest version +1>>"
        LoadBalancerInfo:
          ContainerName: "Fargate-Sec"
          ContainerPort: 80
        PlatformVersion: "LATEST"